steps:

# Uses the docker build step to build an image called serverless-proxy
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/serverless-proxy:$SHORT_SHA', '.']

# serverless-proxy is pushed to Container Registry
images:
- 'asia.gcr.io/$PROJECT_ID/serverless-proxy:$SHORT_SHA'
